name: Publish Python Package to PyPI

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - '!v*.*.*.**' # EXCLUDE tags with more than 3 segments (e.g., v1.0.0.1)
      - '!v*.*.*.*' # EXCLUDE tags with more than 3 segments (e.g., v1.0.0.1)
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Triggers on any tag with 'v.major.minor.patch' format

      #      - 'v[0-9]+.[0-9]+.[0-9]+' # Triggers on any tag with 'v.major.minor.patch' format
#      - '!v*.*.*.**'           # Exclude tags with any additional suffixes (like .dev1)
#      - 'v[0-9].[0-9].[0-9]'    # Matches v1.0.0
#      - 'v[0-9]*.[0-9]*.[0-9]*' # Matches v12.34.56
#      - '!v*.*.*.*'           # Exclude tags with any additional suffixes (like .dev1)
      #   v6.0.2.dev1

#      - 'v[0-9]*.[0-9]*.[0-9]*' # 1. Matches v1.2.3 or v10.22.1
#      - '!v*.*.*.**'           # 2. EXCLUDES any tag with a 4th segment (like .dev1)

jobs:
  build-n-publish:
    name: Build and publish Python üêç distribution üì¶ to PyPI
    runs-on: ubuntu-latest
    
    # Required permissions for Trusted Publishing (OIDC)
    permissions:
      id-token: write
      contents: read

    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: "3.x"

        - name: Install build backend
          run: python -m pip install --upgrade pip build

        - name: Build dists
          run: python -m build

        - name: Publish to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            print-hash: true
